version     = "0.2.0"
author      = "RUI2 Contributors"
description = "RUI2: fast, lightweight reactive UI framework for Nim built on raylib. Umbrella package re-exporting all subsystems."
srcDir      = "src"
# license   = "TODO: choose a license"

requires "nim >= 2.0.0"
requires "naylib"
requires "yaml"
requires "https://github.com/kobi2187/rui_core >= 0.2.0"
requires "https://github.com/kobi2187/rui_hittest >= 0.2.0"
requires "https://github.com/kobi2187/rui_events >= 0.2.0"
requires "https://github.com/kobi2187/rui_drawing >= 0.2.0"
requires "https://github.com/kobi2187/rui_scripting >= 0.2.0"
requires "https://github.com/kobi2187/rui_widgets >= 0.2.0"
