version     = "0.2.0"
author      = "RUI2 Contributors"
description = "RUI2 widgets: primitives (label/rectangle/circle), basic controls (button/checkbox/radiobutton/slider/progressbar/hyperlink/image) and containers (vstack/hstack/zstack/scrollview)."
srcDir      = "src"
# license   = "TODO: choose a license"

requires "nim >= 2.0.0"
requires "naylib"
requires "https://github.com/kobi2187/rui_core >= 0.2.0"
requires "https://github.com/kobi2187/rui_drawing >= 0.2.0"
